### ISSUE TITLE
System flags on damage chat card cannot be accessed via getFlag

### ISSUE THREAD

**Issue by jessev14** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#13]
https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/blob/23cd647e5330ca37828ee28f6817cde615278f3c/scripts/patches/item-damage-patch.mjs#L201

The way flags are currently saved on damage chat cards results in them not being able to be accessed with either getFlag or getProperty. Here's a proposed solution: 
```js
const messageData = {
    user: game.user.id,
    content,
    flavor,
    roll: combinedRoll,
    speaker: ChatMessage.getSpeaker({ actor: item.actor }),
    sound: CONFIG.sounds.dice,
    type: foundry.CONST.CHAT_MESSAGE_TYPES.ROLL,
    flags: {
        "dnd5e": {
            roll: {
                type: "damage",
                itemId: item.id
            }
        },
        "mre-dnd5e": {
            rolls: rolls.map(r => foundry.utils.deepClone(r))
        }
    }
};

if (critical) {
    messageData.flavor += ` (${game.i18n.localize("DND5E.Critical")})`;
    messageData.flags.dnd5e.roll.critical = true;
}
```

As far as I can tell, this issue doesn't break anything, so I don't think it's a high priority fix if the above doesn't work.
-`enso#0361`

**Comment by akrigline** [comment]
this will help us with #12 I'm assuming ;)

**Comment by akrigline** [comment]
From what I can tell, the dnd5e flags are working as expected on the damage cards MRE outputs.
![image](https://user-images.githubusercontent.com/7644614/151488621-ce1b2647-1b75-45bb-8fb8-63ba44ae5f14.png)
