### ISSUE TITLE
What am I doing wrong.

### ISSUE THREAD

**Issue by tposney** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#14]
When I edit an item's damage groups no matter which damage line I select the first damage line insists on being selected. So If I create an item with 2 damage lines and try to have 2 damage groups - no matter what box I check mre insists on setting the first damage line as checked (no matter what I select) and then the second damage line an so on.

In the screenshot below, I selected the third damage line (1d10 lightning) but the first damage line ended up being ticked.

![Screenshot from 2022-01-10 23-09-19](https://user-images.githubusercontent.com/4486143/148763903-0ec340d0-01d6-4a1c-ade1-69e770ed4914.png)

I've tested this in a world with only minimal-roll-enhancements + libwrapper, foundry 9.242/dnd5e 1.5.6, running on linux/node.js

**Comment by akrigline** [comment]
Odd. It doesn't sound like you're doing anything wrong.

Can you try with a fresh item for the sake of it? I've experienced some weirdness with versatile items converted to MRE in the past.

**Comment by akrigline** [comment]
Just reproduced this, will look into it. Thanks for the report!

**Comment by akrigline** [comment]
interesting issue, v9 changed how `input` types of `checkbox` appear in the formData, and apparently we were depending on some assumptions that v9 invaidated. I've adjusted our template and form submission methods to account for the new changes.
