### ISSUE TITLE
[BUG] Damage groups passed the first are not rolled

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#16]
Hello,

FVTT 9.242
MRE 3.2.2

On the following screenshot, two weapons:
- One imported from compendium
- The other manually created with exactly the same configuration

Issues:
- Despite having the same configuration, the two objects don't have the same output in chat
- I don't understand what makes the first item have the keyword "versatile" in the chat card
- The second damage group in the manually created item is not used

![image](https://user-images.githubusercontent.com/1687854/149386825-3bc7431c-9832-4db2-8c40-a4f5c4a2612e.png)

**Comment by akrigline** [comment]
Can you screenshot the formula groups configurations for these two items as well?

**Comment by DarKDinDoN** [comment]
Uh oh, didn't see that button.
Looks like all is OK.
Sorry for the inconvenience !
