### ISSUE TITLE
[FEATURE] Heal/damages buttons

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#17]
Hello,

Not sure if this is a new module or a new feature for this module.
With the suite you are creating, almost everything is covered, but easily applying damage to creatures.

Just like Midi, BetterRolls 5E, etc. Little buttons in the chat card to apply heal/damages would be great.
Right-clicking the chat card is somewhat cumbersome.

**Comment by akrigline** [comment]
Not interested for MRE but I'm considering something like this as a different module.

**Comment by DarKDinDoN** [comment]
@akrigline hoping for a new module then :)
