### ISSUE TITLE
[LANG] FR

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#18]
Hello,

Please find attached the fr.json file for the French language.
[fr.zip](https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/files/7866500/fr.zip)

**Comment by akrigline** [comment]
Hey, sorry I let these sit for a few days, could you open a pull request with these changes instead of an issue with the file attached? That way you'll be credited as a contributor :)

**Comment by DarKDinDoN** [comment]
Here it is: https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/pull/19
