### ISSUE TITLE
Temporary Healing

### ISSUE THREAD

**Issue by aruguy** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#23]
Migrating over from Better Rolls, I notice that MRE doesn't apply temporary healing via right click menu. Is there any way to add in that functionality so that it distinguishes the healing type (when assigned in the item card)?

**Comment by akrigline** [comment]
I had to double check if core 5e does this and it does not. I'm not interested in expanding the MRE module to include more options in the right-click menu, but this is a good idea that could be tackled by another tiny module.
