### ISSUE TITLE
[Bug] Consumable Items Don't Roll

### ISSUE THREAD

**Issue by aruguy** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#24]
Using a consumable item marked to Destroy on Empty will correctly post the item card, but will not retain rollable damage fields if the item has already been removed from the player's sheet (in the case of a single item or last item in a stack).

Example, Player has 2 [SRD] potions of healing. The first one displays the chat card and rolls appropriately. The second one only shows the item card, and the Healing action is non-functional.
![image](https://user-images.githubusercontent.com/12162702/151442013-57557274-1afd-4118-af08-b0b164047e8f.png)

Similarly, after testing with a "grenade" The item will roll an attack value, but healing damage in unresponsive.
![image](https://user-images.githubusercontent.com/12162702/151443255-d1860a9f-5c89-45e3-ab1c-fde821be6495.png)

**Comment by akrigline** [comment]
![Screen Shot 2022-01-27 at 4 06 31 PM](https://user-images.githubusercontent.com/7644614/151443627-ff60fa97-ee60-44e2-a58b-a87a2b7a836f.png)

Guess this might be related to the storage of item data in the chat card.

**Comment by akrigline** [comment]
Fixed in 3.2.6
This little edge case has probably been broken ... for a while... Whoops.
