### ISSUE TITLE
respect the fastforward option in the rollAttack api

### ISSUE THREAD

**Issue by krbz999** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#28]
Setting `advantage: true` or `disadvantage: true` works as intended in `item.rollAttack(),` but the core option of `fastForward: true` has no effect with MRE enabled.

**Comment by akrigline** [comment]
😬 
#22 again... i have regrets

**Comment by akrigline** [comment]
Oh nevermind, this is actually unrelated to #22. Interesting. Thanks for the report.
