### ISSUE TITLE
"debugger" left in the code

### ISSUE THREAD

**Issue by DarKDinDoN** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#32]
Hello,

There is a `debugger` statement left in the code here: https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/blob/master/scripts/patches/ability-check-patches.mjs#L23

**Comment by akrigline** [comment]
Ugh. Lol. Whoops. I guess I should eat my own medicine and implement DevMode debug flags for this finally.
