### ISSUE TITLE
Versatile weapons break with additional damage formulae

### ISSUE THREAD

**Issue by RossGosling** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#34]
**DnD5e 1.5.7, Foundry 9 Build 254**

Vanilla has a separate versatile field, so it's setup as index 0 in the damage formulae array will be overwritten with the versatile field if required:

<img src="https://user-images.githubusercontent.com/879127/156887824-1a707708-ff05-4b32-b10e-23e7ddbf9f9b.png" width="600" height="auto" />

Whereas with MinimalRollingEnchancements enabled it's index 0 as Primary Damage, index 1 as Versatile Damage, and anything beyond is never applied:

<img src="https://user-images.githubusercontent.com/879127/156887978-bee66930-ac42-4188-9e55-a4acd0258572.png" width="600" height="auto" />

**Comment by akrigline** [comment]
Click on the little icon next to "damage formula" heading to configure which damage parts are used for what damage roll. I believe that will sort you out.

**Comment by RossGosling** [comment]
Ah, yes! you're totally right, that is a great feature I had no knowledge of, sorry about that!

For reference:

<img src="https://user-images.githubusercontent.com/879127/156889564-7099064e-00b6-439a-b65f-539105a042d6.png" width="600" height="auto" />
