### ISSUE TITLE
Can only apply total damage

### ISSUE THREAD

**Issue by PaulWRoberts** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#37]
If I have multiple damage sources in a single attack and I right click to apply damage, it will apply the total. Even when I do not have the "show total" option selected. This makes it fiddly to apply resistances or optional damage (like +x extra to undead).

I would expect when I right click an individual damage roll to be able to apply the damage from that roll only. Creating entirely new groups does not work for this workflow because spell scaling formulas are added to each group. Additionally, there is no way to make all groups auto-roll.

**Comment by akrigline** [comment]
This is how MRE is set up to handle things by default.

Right clicking on the individual results allows application of those individual damage instances, but right clicking on the chat card overall allows application of the total.
![2022-04-18 10 54 37](https://user-images.githubusercontent.com/7644614/163826940-bed1479b-10ff-47ce-8c5b-2d698b7d53e6.gif)

**Comment by PaulWRoberts** [comment]
Then that is the bug, this doesn't happen. There is something wrong with my environment, because if I enable only MRE I do not get this behavior. But I use it in a new world I do not.
