### ISSUE TITLE
[Bug] Damage Context menu frequently does not display

### ISSUE THREAD

**Issue by PaulWRoberts** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#38]
The damage context menu frequently does not display when right clicking on a damage formula. This occurs without other modules installed. The behavior is not consistent and enabling and disabling other modules appears to impact it. But I can confirm that this behavior occurs with MRE the only module enabled.

My debugging showed that when it worked the selector was mre-damage-card, and when it did not occur the selector was chat-message. However, I was hovering the correct part of the chat message and the element did have the mre-damage-card class.

**Comment by akrigline** [comment]
Can you show me the items you used to make this happen? Also thanks for looking more into this. Getting some consistent reproduction steps is the first step to finding this bug.

**Comment by PaulWRoberts** [comment]
![image](https://user-images.githubusercontent.com/5503568/163877522-4528fdbf-b7a3-404f-9b23-fc252b6de2d8.png)
This is the weapon I create. To repro the issue I made a new world, put in a single blank scene and krusk from the starter heroes, and an acolyte for this target. I enable MRE and set autoroll hit and damage. I add a flametongue weapon from the items compendium, equip it on krusk and move the 2d6 from the other formula to be fire damage and part of the primary group, as shown in the screenshot. I attack the acolyte as the target with the weapon. It usually works as expected. Logging out and in again and trying to apply damage from the previous session usually, but not always, is able to repro the issue.

**Comment by PaulWRoberts** [comment]
I have been able to repro this consistently just now.
I clear my chat log -> refresh -> make the attack -> the right click context menu is correct.
Then I refresh -> the right click context menu is incorrect.

This process is then repeatable.

**Comment by PaulWRoberts** [comment]
ContextMenu.create(this, html, ".message", this._getEntryContextOptions());

is called AFTER

new ContextMenu(ui.chat.element, ".mre-damage-card .dice-result", contextOptions);

when there is **already a damage message in chat history**.

yet the order is reversed when there is no existing chat message.

It appears that when a single context menu is able to nested selectors - as is the case for the damage chat message, that the last one registered is the only one which is checked. So, a naive solution would be to ensure that MRE selector is always registered last.

**Comment by PaulWRoberts** [comment]
Ok, this is a race condition which is why it usually is so inconsistent.
In setupGame which is called when you refresh the page the last thing it does is call await Hooks.callAll("ready") which is where the context menu with the mre selector is created. Yet earlier in setupGame initializeUI is called and inside that method is an async render call, in which the default message context menu is registered.

So, if rendering the UI takes long enough the the async call to render is still processing while the ready hooks are completed this happens. I believe in my test case this occurs when the chat has messages in it. But as is the nature of race conditions there is no guarantee here.

I'm not sure how to fix this, the right solution might be to not use nested context menus? Perhaps a button overlay on the damage card?

**Comment by PaulWRoberts** [comment]
Ok, I locally changed
https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/blob/master/scripts/hooks/damage-card-context-menu.mjs#L26

from
`Hooks.once("ready", async () => {`
to
`Hooks.once("renderChatLog", async () => {`

and it seems to have fixed it. But considering it is a race condition it will require more testing. I will keep you updated.

**Comment by PaulWRoberts** [comment]
The default context menu for a message is registered in render chat log, so if the hook to register the override context menu is moved to be on render chat log, rather than on ready this issue is solved. It would not address any incompatibility with chat message context menu overrides.

I will submit a PR for this.
