### ISSUE TITLE
Clicking on any "Auto Roll" button on an item sheet for an item that you do not own reloads the page and breaks the layout

### ISSUE THREAD

**Issue by schultzcole** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#42]
I guess this is because it is a `button`, and in the case that the item is not owned, we don't prevent default on those.

**Comment by schultzcole** [comment]
I'll submit a PR to change these to be not a button. Really they should actually be checkboxes... not sure why I didn't just do that to begin with.

**Comment by akrigline** [comment]
I think because they have three states: override yes, override no, and _null_ aka "no override"

**Comment by schultzcole** [comment]
I think we can bypass that by using the built in indeterminate prop on checkboxes: https://css-tricks.com/indeterminate-checkboxes/

We'll still need some logic to translate checked property and indeterminate property to the form we want, but I think using a native control similar to our goals is less likely to do something unexpected. I think it would also be useful to use a native control because that is less likely to be incompatible with layout/styling in non-core item sheets.

**Comment by akrigline** [comment]
Yeah I'm game.
Indeterminate would be the "default no override" state?
Checked is "override yes"
And unchecked is "override no"?

**Comment by schultzcole** [comment]
Exactly

**Comment by akrigline** [comment]
I'll get a release out with #43 soon™

**Comment by akrigline** [comment]
4.1.0 released
