### ISSUE TITLE
Request: Optional damage roll formatting

### ISSUE THREAD

**Issue by krbz999** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#47]
When damage rolls have two or three damage formulas in one group, combined with the Total underneath, the chat cards become way too big for my tastes.
Would it be possible to have a setting that retains the default flavor text (e.g., `Damage Roll (Piercing, Fire, Thunder)`), thus letting the dice rolls be vertically shorter.

Alternatively, and maybe more ideally, combined with a hover effect as with the dice rolls, such that hovering over the individual totals show the damage type (this is in combo with Compact Roll Cards, forgot that part).

**Comment by akrigline** [comment]
MRE has been around long enough that I'm not keen on doing much of a redesign. What we have works and I'm happy with it. If we were to do some redesign work, I would not want to have it exist behind a setting.

@cole if you're down to give it a shot go for it, but I'm not terribly interested in such a refactor on this pretty stable module.

**Comment by krbz999** [comment]
Admittedly didn't realize it would require a refactor to do. It would be nice but not a big enough deal for me to risk causing instability.
