### ISSUE TITLE
Only Rolls First 2 Damage Sources

### ISSUE THREAD

**Issue by SDoehren** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#48]
Only the first 2 damage sources roll.  The Third onwards are ignored.
![image](https://user-images.githubusercontent.com/41287460/179364217-56758066-f25d-4d0a-aa08-8ce2b24603c3.png)

**Comment by akrigline** [comment]
Can you check the damage group configuration? It's possible that the third roll isn't assigned to any group.

The little button next to the "Damage Formula" heading.

**Comment by SDoehren** [comment]
That was exactly it!
