### ISSUE TITLE
Versatile Damage Field disappears when MRE is active in the world

### ISSUE THREAD

**Issue by deraviin** [ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#49]
The versatile damage field normally present in a weapons damage disappears and turns the field into a normal damage field in the weapons details. 

This is all fine and good until you are making a custom weapon and cannot add versatile damage in a way that is triggered by the chat cards, or in my example Polearm Mastery damage.

This seems to be an intentional change, so I'm wondering what I'm missing in terms of editing an item with MRE active. I can of course disable it and edit the item, but this seems a bit strange. 
![nomre](https://user-images.githubusercontent.com/46595619/180345224-4dbe10c9-0797-43d0-ad24-89fcea3b36fa.png)
![mre](https://user-images.githubusercontent.com/46595619/180345234-cb729284-d749-4462-8ab6-e971877c1234.png)
.

**Comment by akrigline** [comment]
This is indeed intentional.

Use the little button next to "damage formula" to create damage groups.

These damage groups can be set up to replace "main" and "versatile" damage configs.

**Comment by deraviin** [comment]
I see. Thanks for the confirmation!
